version: '3.8'
services:
  api:
    build: .
    container_name: api
    env_file:
      - config/local.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - relational_db

  redis:
    image: redis
    container_name: redis
    env_file:
      - config/local.env
    ports:
      - "6000:6379"

  relational_db:
    image: postgres
    container_name: postgres
    env_file:
      - config/local.env
    ports:
      - "5450:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_DB: "${POSTGRES_DB}"