services:
  api:
    build: .
    container_name: api
    env_file:
      - config/local.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rabbitmq
      - relational_db
      - non_relational_db

  redis:
    image: redis
    container_name: redis
    env_file:
      - config/local.env
    ports:
      - "${REDIS_PORT}:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    env_file:
      - config/local.env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  relational_db:
    image: postgres
    container_name: postgres
    env_file:
      - config/local.env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_DB: "${POSTGRES_DB}"
    
  non_relational_db:
    image: mongo:7.0
    container_name: mongo
    env_file:
      - config/local.env

volumes:
  rabbitmq_data: