version: '3.8'
services:
  api:
    build: .
    container_name: api
    env_file:
      - config/local.env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - rabbitmq
      - relational_db

  redis:
    image: redis
    container_name: redis
    env_file:
      - config/local.env
    ports:
      - "6000:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    env_file:
      - config/local.env
    ports:
      - "5672:5672"      # AMQP port
      - "15672:15672"    # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  relational_db:
    image: postgres
    container_name: postgres
    env_file:
      - config/local.env
    ports:
      - "5450:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_DB: "${POSTGRES_DB}"

volumes:
  rabbitmq_data: